### ISSUE TITLE
Profile

### ISSUE THREAD

**Issue by shenxwang** [mozilla/m-response#110]
### Profile
**(Page name is matching with the artboard name in Zeplin)**

@abigail-hampson 
- [ ] 1. The spacing between the Title and the edge of the screen
- [ ] 2. The spacing and size of the profile placeholder, radius 4
- [ ] 3. The spacing and style of the user's name and language
- [ ] 4. Size and style(radius 4) of the record banner
- [ ] 5. The spacing, size, style of the Response, Moderations, Karma badge & caption
- [ ] 6. Background color(#F9F9FA)
- [ ] 7. Spacing and size of the button, and the style of the button text.
![artboard1](https://user-images.githubusercontent.com/44074748/47059795-d3982d80-d198-11e8-9a26-13269a252156.png)

**Comment by BhuvanaMeenakshiK** [comment]
When I hover my mouse cursor towards the my initial I thought it will direct me to my profile but sadly it did not. Instead I have to everytime edit my url to go to my profile page.
![untitled](https://user-images.githubusercontent.com/36270367/50073507-d3e79000-01fe-11e9-8072-bd0a82504016.png)
