### ISSUE TITLE
Response guidebook - hardcoded link

### ISSUE THREAD

**Issue by abigail-hampson** [mozilla/m-response#117]
@madasan do you have the URL for this?

**Comment by rtanglao** [comment]
i believe @turtlelovesshoes i.e. rachel mcguigan can dig up this link for you madalina and abigail, otherwise Lucy and Konstatina will know as well since L&K did it for the first version of this tool

**Comment by tm-kn** [comment]
We're also missing legacy, privacy and cookie links.

**Comment by turtlelovesshoes** [comment]
https://docs.google.com/document/d/1dtTS0hAIYyf9JWoqPc_S2tg2XmdptVYI06koGCZwiXc/edit 

Legacy - not sure what you mean, legal? - look at the links in the footer of every mozilla.org page like this one: https://www.mozilla.org/en-US/privacy/firefox/ 
Privacy - general Mozilla Link - https://www.mozilla.org/en-US/privacy/firefox/
Cookie - https://www.mozilla.org/en-US/privacy/websites/#cookies

**Comment by tm-kn** [comment]
Hi @turtlelovesshoes, do you want to link to that Google doc from the app? I think we should host it somewhere. We could host it on the application itself, but you'd need to provide us with a PDF. /cc @madasan

**Comment by madasan** [comment]
Yes, we want the Google doc to be linked from the app.

The doc has been published to the web, will that suffice? I can provide the link and embed code.
A PDF is also an option, it will just be a bit difficult to update. 

Let me know what you prefer.

**Comment by tm-kn** [comment]
Hi, publishing it to the web should be fine. Although it has not been published, it seems. I still need to request the access to it.

**Comment by madasan** [comment]
Try this link: https://docs.google.com/document/d/e/2PACX-1vQds-2DY62ztTCyaoyVr5myp5ZszUFhAyfGueTz5OF9Gi5UibS9LoMxAFkkMhlaH133WF6M3bggD8K4/pub

Embed code: <iframe src="https://docs.google.com/document/d/e/2PACX-1vQds-2DY62ztTCyaoyVr5myp5ZszUFhAyfGueTz5OF9Gi5UibS9LoMxAFkkMhlaH133WF6M3bggD8K4/pub?embedded=true"></iframe>

**Comment by tm-kn** [comment]
Thanks. I've added the link to the API.
