### ISSUE TITLE
Moderation queue number bug

### ISSUE THREAD

**Issue by decode-dev** [mozilla/m-response#223]
Moderation queue displays the number but when clicked it shows "Error! No responses available in the moderator queue."
![mzr](https://user-images.githubusercontent.com/6382146/49153219-1ffb8f00-f33b-11e8-8024-c3cb99e65ce2.JPG)
![mzr1](https://user-images.githubusercontent.com/6382146/49153220-1ffb8f00-f33b-11e8-9626-da70e99d5410.JPG)

**Comment by kelimuttu** [comment]
Bhuvana got the same error as well 

![photo_2018-12-14_19-49-23](https://user-images.githubusercontent.com/4922388/50004303-61499b00-ffd9-11e8-8629-3dffde713fd7.jpg)

![photo_2018-12-14_19-49-19](https://user-images.githubusercontent.com/4922388/50004318-6c9cc680-ffd9-11e8-90e3-8b0830abb3bf.jpg)

**Comment by kelimuttu** [comment]
And now I got the same issue as well 

![screenshot_2018-12-14 mozilla respond](https://user-images.githubusercontent.com/4922388/50004907-2b0d1b00-ffdb-11e8-951b-c0e55dd75368.png)

![screenshot_2018-12-14 mozilla respond 1](https://user-images.githubusercontent.com/4922388/50004923-32342900-ffdb-11e8-92fc-72b22e58b629.png)
