### ISSUE TITLE
Simplified moderation flow - display moderation box immediately

### ISSUE THREAD

**Issue by natalieblackburn** [mozilla/m-response#249]
Acceptance criteria:

As a normal user (not in a trusted user/moderator group): 

- 3 moderation questions and submit button display in the initial view of a response to moderate
 - I am able to 'skip' to select another response to moderate 

Current designs here: https://scene.zeplin.io/project/5ca60faab94a0d6c240571a5

**Comment by thisoldbear** [comment]
This has been deployed to staging

**Comment by natalieblackburn** [comment]
This looks good to me, tested with user tbx-test-1 who is not in the trusted user groups. Good for you to test and confirm Madalina

**Comment by madasan** [comment]
This is working fine
