### ISSUE TITLE
Simplified moderation flow - option to approve or moderate

### ISSUE THREAD

**Issue by natalieblackburn** [mozilla/m-response#250]
Acceptance criteria:

- As a user belonging to one of the trusted user groups, when I see a response listed, I am able to select to 'approve' or 'moderate', as well as the link to 'skip'
 - If I select to moderate, the usual moderation questions display

Wireframe: https://miro.com/app/board/o9J_kxugMxg=/?moveToWidget=3074457346568046365

**Comment by tm-kn** [comment]
See #259 for API details.

**Comment by thisoldbear** [comment]
Dependent on work for #249 (currently in PR here: https://github.com/mozilla/m-response/pull/265/) being on `phase-two` branch.

**Comment by thisoldbear** [comment]
@natalieblackburn This has been deployed to staging
