### ISSUE TITLE
Simplified moderation flow - add message

### ISSUE THREAD

**Issue by natalieblackburn** [mozilla/m-response#251]
Acceptance criteria:

 - As a user belonging to one of the trusted user groups, I am able to add a feedback message when moderating a response
 - The message is stored in the database

Wireframe: https://miro.com/app/board/o9J_kxugMxg=/?moveToWidget=3074457346568046370

**Comment by tm-kn** [comment]
`feedback_message` field added to the API.

**Comment by thisoldbear** [comment]
@natalieblackburn Have asked Helen C to take a look if possible.

**Comment by natalieblackburn** [comment]
I can see the field fine, doesn't seem to be submitting though. Is that a BE issue or FE?

**Comment by thisoldbear** [comment]
@natalieblackburn I was able to submit the form with a message. It may have been an intermittent issue.
