### ISSUE TITLE
Remove reward responder

### ISSUE THREAD

**Issue by natalieblackburn** [mozilla/m-response#252]
Acceptance criteria:

 - When moderating a response, there is no longer a sliding bar to change the karma points that the responder receives
 - Responses are given a fixed karma amount of 1 (TBC by Madalina)

Current designs here: https://scene.zeplin.io/project/5ca60faab94a0d6c240571a5/screen/5cf6216f07ad921abf0daf4e

**Comment by tm-kn** [comment]
@thisoldbear I've deleted the `karma_points` field in the API for moderations. Feel free to pick it up.

**Comment by thisoldbear** [comment]
@tm-kn I've removed the karma slider (and related markup, styles, packages) and the passing of the value via Redux to the request.

https://github.com/mozilla/m-response/pull/264

If it looks good to you, I'll merge it.

**Comment by natalieblackburn** [comment]
This is working fine for me, ready for Mozilla testing

**Comment by madasan** [comment]
This is working fine
