### ISSUE TITLE
Trusted users - add permissions

### ISSUE THREAD

**Issue by natalieblackburn** [mozilla/m-response#253]
Acceptance criteria:

 - As a user in the '1st level trusted user', I can instantly approve the responses of other users, bypassing further community moderation
 - As a user in the '2nd level trusted user' group, I can instantly approve the responses of other users, bypassing community and staff moderation
 - Moderation flow is updated to reflect these new permissions

**Comment by tm-kn** [comment]
Can be tested after #250 is done.

**Comment by madasan** [comment]
Steps to reproduce:
- Logged in with a user in the 1st level trusted group (madalina_mod1)
- When trying to Approve or Moderate  I get an error "Unable to approve the response"

![image](https://user-images.githubusercontent.com/10244340/59488725-2368ea80-8e35-11e9-8348-620fd31c200e.png)

**Comment by natalieblackburn** [comment]
I'm seeing the same error for users who aren't admins in these groups, getting some developer time to investigate further

**Comment by madasan** [comment]
I still get an error when moderating as an user in the 1st and 2nd level groups. This seems to happen only when leaving a feedback message. Moderating without the feedback message works fine. Approvals work fine.
![image](https://user-images.githubusercontent.com/10244340/59737221-9bf2f100-9211-11e9-9ccd-519001406dff.png)

**Comment by madasan** [comment]
Testing this in production:

Steps to reproduce:
Log in to the admin console. Select a user to change.

Expected behaviour:
I should be able to add the user to either 1st Level Trusted or 2nd Level Trusted groups.

Actual behaviour
There are no groups available.

![image](https://user-images.githubusercontent.com/10244340/59938834-f30fe600-940a-11e9-8a7b-83904528af25.png)

**Comment by tm-kn** [comment]
@madasan The groups are not created automatically. You need to create them manually and assign "Can bypass community moderation" and "Can bypass staff moderation" accordingly.

**Comment by madasan** [comment]
Got it. OK, it seems to work now.
