### ISSUE TITLE
Update moderation question copy

### ISSUE THREAD

**Issue by natalieblackburn** [mozilla/m-response#254]
Copy to be supplied by Madalina

**Comment by madasan** [comment]
New moderation questions copy:

Does this response feel friendly?
Is this response technically accurate?
Would you reuse this response for a similar question?

![image](https://user-images.githubusercontent.com/10244340/59019364-97612c80-8850-11e9-87ad-ce9df3c83df5.png)

**Comment by natalieblackburn** [comment]
This looks OK to me, ready for your testing Madalina

**Comment by madasan** [comment]
This is working fine

**Comment by madasan** [comment]
Ok on prod.
