### ISSUE TITLE
Leaderboard API view

### ISSUE THREAD

**Issue by natalieblackburn** [mozilla/m-response#255]
- Leaderboard is calculated based 50% on number of submissions and 50% on number of moderations
 - Leaderboard is updated weekly

**Comment by tm-kn** [comment]
This waits to be integrated with #256 and then can be tested.

**Comment by natalieblackburn** [comment]
This one is a little tricky to test on staging as it updates once a week (as agreed). It looked OK when I tested last week when there were 3 test users with enough activity to put them into the leaderboard and displayed as expected.

**Comment by tm-kn** [comment]
@natalieblackburn The view is obviously refreshed every week + it's cached. We could disable caching for the testing if that's necessary.

**Comment by natalieblackburn** [comment]
Thanks Tomasz, yes I agree it's definitely working as we thought it would. If you could disable caching for it on staging to help testing that will help!
