### ISSUE TITLE
Leaderboard dashboard

### ISSUE THREAD

**Issue by natalieblackburn** [mozilla/m-response#256]
Acceptance criteria:

 - On first load of the app, the leaderboard dashboard displays below the 'respond' and 'moderate' options
 - The leaderboard displays the top 3 users, followed by a table of X number of users (TBC)

Wireframe: https://miro.com/app/board/o9J_kxugMxg=/?moveToWidget=3074457346568046372

**Comment by madasan** [comment]
Testing in prod

The leaderboard dashboard doesn't seem to be available, it's a blank box

![image](https://user-images.githubusercontent.com/10244340/59946192-b2ba6300-941e-11e9-8ddd-0dae020a5692.png)

**Comment by tm-kn** [comment]
The last generated leaderboard was on the 1st of July. Next due one would be on Monday, 8th July. It seems that there just wasn't any responses/moderations before the 1st of July. I've manually generated a new leaderboard.

**Comment by madasan** [comment]
@tm-kn It looks like this week it is blank again, I suspect it is because of low activity. Can we review what are the minimum requirements for the dashboard to be generated? (I assume at least 3 users who have submitted at least 1 response and 1 moderation or something similar).

**Comment by tm-kn** [comment]
@madasan Sorry, it is a bug. It generated leaderboard for the current week where it should generate it for the previous. I've submitted a pull request #256 to fix that.

**Comment by tm-kn** [comment]
I've deployed the fix @madasan . This should work as expected now.
