### ISSUE TITLE
Enduring success messages 

### ISSUE THREAD

**Issue by mcroud** [mozilla/m-response#276]
Clicking “Skip” on a response or moderating a response doesn’t close an existing “success” message. Existing success messages remain even after skipping and moderating which can start to build up a queue of messages which have to be manually closed.

<img width="489" alt="Screenshot 2019-06-21 at 11 49 47" src="https://user-images.githubusercontent.com/42435754/59944825-b2b86400-941a-11e9-8298-05d215fe7c94.png">

**Comment by rleitan** [comment]
@johngian should I be able to see the fix in https://mresponse-staging.herokuapp.com?
The issue is still reproducible on Moderate and on Respond, the Skip button is not working

**Comment by rleitan** [comment]
On prod env: https://respond.mozilla.community/, following the STR:
1. Go to respond section and add a response -> Success message and new response are displayed
2. Click "Skip" button ->Success message disappears and the same response is displayed (see [video](https://drive.google.com/file/d/1BOR5c5tk0ALFZg7VWeAQfMrRkh_bN25z/view))

Looks like "Skip" button works for dismissing the success message not for skiping the response
@madasan is this expected?
