### ISSUE TITLE
Moderator responses should not appear in the moderation queue

### ISSUE THREAD

**Issue by madasan** [mozilla/m-response#288]
[STR]:
1. Log in as Moderator Level 1
2. Open https://respond.mozilla.community/moderate/

[Expected result]:
I should only see responses from users who do not have moderator permissions. Responses from moderators should automatically bypass community moderation.

[Actual result]:
I can see responses in the queue submitted by other level 1 moderators.

![image](https://user-images.githubusercontent.com/10244340/60812897-36a07900-a19b-11e9-93ee-5e99ee9eb4dd.png)

**Comment by johngian** [comment]
I tried to verify this but it looks like responses from moderators are automatically approved. The problem here is that if you directly approve something their would be no moderations and we show elements in the queue based on that.

@madasan thoughts?

**Comment by madasan** [comment]
Understood, let's fake three YES moderations.
