### ISSUE TITLE
A response is marked as ready to be submitted to Play store after a 1st level user responded

### ISSUE THREAD

**Issue by rleitan** [mozilla/m-response#321]
[STR]:
1.Add a response from a 1st level account

[Expected result]:
The response should not be marked as Approved ( "If response meets criteria to be submitted to the Play Store.”)

[Actual result]:
Admin interface: the response it’s marked as “ If response meets criteria to be submitted to the Play Store.” Approved.

@madasan is this expected?

**Comment by madasan** [comment]
The response should be approved from a community point of view but not staff approved.
