### ISSUE TITLE
In Moderate section are displayed responses in languages that are not added in the account

### ISSUE THREAD

**Issue by rleitan** [mozilla/m-response#322]
[Precondition]:
Create a 2nd level account and add only the English language

[STR]:
1.Log in with the account from Precondition
2.Go to Moderate

[Expected result]:
Should be displayed only English responses

[Actual result]:
There are displayed responses in French

**Comment by rleitan** [comment]
If I had a language in my account(e.g. english, german,french) -> I can see a review in that language(french), then I removed the language from Settings, the review should be still available in respond after reloading the page? Should be updated only after re-login?
https://drive.google.com/file/d/1R_SbJX04cLAGTFDU9VuquVEn2qAS-CP1/view
Still, I consider it a bug because it's displayed 0 reviews in Respond queue and the "french" one is still displayed

@madasan @johngian

**Comment by johngian** [comment]
It should show proper languages after a refresh.

**Comment by johngian** [comment]
@rleitan I think the main problem here is that by default we serve English reviews to everyone.
@madasan thoughts? Should we not serve English by default? It's hardcoded in the codebase since the first iteration.

**Comment by johngian** [comment]
Also another problem i found is that we show the user assigned responses by default. If the user changes their language they are stuck with the old assigned review.
