### ISSUE TITLE
BE: Add an edited message field to the API moderation view that will alter the response message. Add a Django admin log of that action.

### ISSUE THREAD

**Issue by madasan** [mozilla/m-response#335]

**Comment by rleitan** [comment]
I don't see anything related to edited response in the admin interface.
@vbabiy @M-erb can you please add a screenshot with how and where should be displayed?

**Comment by viorelaioia** [comment]
This is still happening, there is no log of edited response in the admin.

**Comment by vbabiy** [comment]
> ok so people in moderator 1 or moderator 2 groups should have the permission to edit other people’s responses

**Comment by rleitan** [comment]
I can see the edited response in the admin interface, but I am not able to see anything related to "Add a Django admin log of that action".
@vbabiy

**Comment by viorelaioia** [comment]
The log of the change is displayed in admin -> Response page => History
