### ISSUE TITLE
BE: API for moderation queue

### ISSUE THREAD

**Issue by madasan** [mozilla/m-response#340]
Must include:

* Response text
* Karma points
* Number of times it has been moderated

**Comment by rleitan** [comment]
Karma points are not displayed as per [designs](https://app.zeplin.io/project/5ca60faab94a0d6c240571a5/screen/5d42d15164e8c22bd5bff8e0)

**Comment by rleitan** [comment]
> Karma points are not displayed as per [designs](https://app.zeplin.io/project/5ca60faab94a0d6c240571a5/screen/5d42d15164e8c22bd5bff8e0)

Karma points are still not displayed

@M-erb
