### ISSUE TITLE
"Get help" from Response and Moderate sections shows "Canned Responses" in title

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/m-response#351]
**STR:**

1. Login to respond tool staging
2. Navigate to Respond module
3. Click "?" from the top right side

**Expected:**
Title saying "Help & Documentation" is shown

**Actual:**
Title saying "Canned Responses" is displayed. 
Same happens if the user navigates to Moderate module and taps the "?". 

![photo5947357424157569017](https://user-images.githubusercontent.com/5293100/62853918-7b698380-bcf6-11e9-8ec1-7b9b34e7de2d.jpg)

**Comment by madasan** [comment]
Seems to have been fixed
