### ISSUE TITLE
Add underline style for "Help Docs" link on Homepage

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/m-response#359]
As per [designs](https://miro.com/app/board/o9J_kx_hR4k=/), "Help Docs" link should be underlined. 

![photo_2019-08-14_11-53-01](https://user-images.githubusercontent.com/5293100/63019573-6f232900-bea4-11e9-9473-340460809d2e.jpg)

**Comment by Patil2099** [comment]
@viorelaioia  There is no help docs in \m-response\mresponse\frontend\app\src\pages\home\home.js
Do I have to add Help Docs and then add styling to it?
