### ISSUE TITLE
Large text in Canned Responses is not pasted entirely in the Respond input field 

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/m-response#360]
**Precondition:**
Have a response of large text for a category in Canned responses

**STR:**

1. Navigate to Respond module 
2. Click Respond button for one of the available reviews
3. Click Canned Responses button
4. Copy the response of large text created in precondition
5. Paste the text in the input field

**Expected:**
Text is pasted entirely

**Actual:**
Text is pasted partially, Respond input field seems to have a limit of 340 characters 

![image](https://user-images.githubusercontent.com/5293100/63020198-1ce30780-bea6-11e9-9b95-18cc42f2fd3f.png)
![image](https://user-images.githubusercontent.com/5293100/63020265-5451b400-bea6-11e9-8af7-0132f0cbf17b.png)

**Comment by M-erb** [comment]
Good find. Looking into this I found that the tap/click is copying all of the text. You can check this by pasting into a different place like a note or word processor app after copying. It is actually the text area box that is limited to 340 characters. The google play API has limited responses to 350 characters and talking with the team we are changing this to a 350 limit instead and adding a character counter at the bottom of the textarea.

**Comment by rleitan** [comment]
> Good find. Looking into this I found that the tap/click is copying all of the text. You can check this by pasting into a different place like a note or word processor app after copying. It is actually the text area box that is limited to 340 characters. The google play API has limited responses to 350 characters and talking with the team we are changing this to a 350 limit instead and adding a character counter at the bottom of the textarea.

In this case, should be limited to 350 in the admin too.

**Comment by rleitan** [comment]
I'm still able to add in the admin interface, canned responses with more than 350 characters

**Comment by viorelaioia** [comment]
@vbabiy , @M-erb , current limit to canned response in the admin interface is set to 361 characters, instead of 350. Can you please update it to allow only 350 characters? Thanks!
