### ISSUE TITLE
TypeError: Cannot read property 'positive_in_tone_count' when opening the dashboard

### ISSUE THREAD

**Issue by rleitan** [mozilla/m-response#364]
[Precondition]:
Log in https://mresponse-staging.herokuapp.com then close the browser

[STR]:
1.Open https://mresponse-staging.herokuapp.com

[Expected result]:
The page should be loaded

[Actual result]:
The URL is redirected to https://mresponse-staging.herokuapp.com/dashboard/ and blank page is displayed
Browser console:
Uncaught (in promise) TypeError: Cannot read property 'positive_in_tone_count' of undefined
    at c (index.js:55)
    at Function.c [as mapToProps] (index.js:15)
    at r (wrapMapToProps.js:41)
    at Function.r.mapToProps (wrapMapToProps.js:50)
    at r (wrapMapToProps.js:41)
    at i (selectorFactory.js:22)
    at selectorFactory.js:63
    at Object.run (connectAdvanced.js:21)
    at l.f.initSelector (connectAdvanced.js:180)
    at new l (connectAdvanced.js:118)

[Note]:
Reloading the page doesn't fix the issue
The issue is not reproducible in private tab

**Comment by mcroud** [comment]
I am also unable to see the app, instead being presented with a blank page.
I seem to get a different console error:

<img width="549" alt="Screenshot 2019-08-20 at 09 39 10" src="https://user-images.githubusercontent.com/42435754/63331856-6d3ae900-c32e-11e9-984f-cf7c0a880a33.png">

**Comment by M-erb** [comment]
Tested in Firefox and Chrome with no issues or errors displayed. Due to it working for you in a private tab I suspect that your browser's cached version of the app is conflicting with changes to the API. So clearing cache and cookies should clear that up.

**Comment by johngian** [comment]
Looks like it picked up the changes in prod. Works fine now.
