### ISSUE TITLE
Feedback stats "total' figure styling

### ISSUE THREAD

**Issue by mcroud** [mozilla/m-response#377]
The "total" figure presenting on the user's weekly stats graph should be visually distinct from the "current" figure.

On staging we see them styled the same:

<img width="557" alt="Screenshot 2019-08-30 at 15 44 19" src="https://user-images.githubusercontent.com/42435754/64029771-28d4f780-cb3d-11e9-8ecc-aaa0bcbc9a66.png">

The Zeplin designs show that they should be smaller in size and a lighter grey:

<img width="243" alt="Screenshot 2019-08-30 at 15 47 03" src="https://user-images.githubusercontent.com/42435754/64029932-7a7d8200-cb3d-11e9-991e-1435423bb7d3.png">

The styles captured in Zeplin are:

 ```
{
  width: 19px;
  height: 21px;
  font-family: OpenSans;
  font-size: 12px;
  font-weight: normal;
  font-style: normal;
  font-stretch: normal;
  line-height: 1.75;
  letter-spacing: normal;
  color: #4a4a4f;
}


```

**Comment by mcroud** [comment]
The colour is looking good now, thanks! Can I just be nit-picky and request it appears `12px` so that it renders slightly smaller than the "current" number to its right?

**Comment by M-erb** [comment]
@mcroud Not a problem. Made the change. You should see this change once I get this back into the QA on staging column/bucket on the kanban board
