### ISSUE TITLE
Card top borders are the wrong colour

### ISSUE THREAD

**Issue by mcroud** [mozilla/m-response#379]
On staging the card top borders in Moderate are `#0060df`:

<img width="701" alt="Screenshot 2019-08-30 at 16 16 16" src="https://user-images.githubusercontent.com/42435754/64032850-38573f00-cb43-11e9-9f0b-66926624193e.png">

They should be`#00ddff` for Moderate:

<img width="851" alt="Screenshot 2019-08-30 at 16 30 23" src="https://user-images.githubusercontent.com/42435754/64033009-7fddcb00-cb43-11e9-87ba-a602bcdf3ed8.png">

and `#ffa266` in Respond

<img width="881" alt="Screenshot 2019-08-30 at 16 31 17" src="https://user-images.githubusercontent.com/42435754/64033065-9c7a0300-cb43-11e9-95ae-c73e38854779.png">

**Comment by mcroud** [comment]
Blue looks good! The Respond cards need to have a top-border colour of `#ffa266`. Currently it is `#ffd5b2`.

**Comment by rleitan** [comment]
> Blue looks good! The Respond cards need to have a top-border colour of `#ffa266`. Currently it is `#ffd5b2`.

@M-erb
