### ISSUE TITLE
User is always redirected to the 1st page, after moderating a response

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/m-response#384]
**Env:**
iPhone X, iOS 12.4, latest Firefox and Safari

**STR:**
Login to Respond 
Tap "Moderate" section
Navigate to a different page (e.g: page 4)
Select a response and moderate it
Tap Submit button

**Expected:**
Success message is displayed, user is on the page he was previously (page 4)

**Actual:**
Success message is displayed, user is redirected to first page. See [video](Success message is displayed, user is)

**Comment by rleitan** [comment]
verified as fixed!
