### ISSUE TITLE
As an admin I should be able to identify trusted contributors in the app so that I know who has special privileges

### ISSUE THREAD

**Issue by rleitan** [mozilla/m-response#387]
Moderator badges can only be visible to other people if those people have Admin privileges

**Comment by rleitan** [comment]
Please see line 21-D from https://docs.google.com/spreadsheets/d/1z5G0fmYc0cpNIuIQhExFDdvG7wcDukzx40nslR7Qo0E/edit#gid=1262571894

The moderator badges should be visible to:
1.self 
2.admins- should be able to see moderator badges for all users

**Comment by madasan** [comment]
Visibility to self is a requirement for pushing to prod.
Visibility to admins is minor and we can defer it to a later date.
