### ISSUE TITLE
Create notification banner

### ISSUE THREAD

**Issue by M-erb** [mozilla/m-response#391]

**Comment by rleitan** [comment]
@M-erb what are the conditions for this [one](https://app.zeplin.io/project/5ca60faab94a0d6c240571a5/screen/5d42bdaefab49788a2e2c6a4) to be displayed?

**Comment by mcroud** [comment]
Following on from today's call- a very good question and it took me a while to find an answer. The user journey in Miro only displays "Feedback Sent". The Prototype on Invision however has the message "Response moderated".

The "Response moderated" was brought in when a Moderator clicks the instant Approve button. It didn't really feel like feedback but more of an insta-approve so "Response moderated" seemed more accurate. 

<img width="442" alt="Screenshot 2019-09-26 at 18 06 03" src="https://user-images.githubusercontent.com/42435754/65709268-53589880-e088-11e9-966c-ff0f526fe9c4.png">

Really though, this might as well say "Response approved" and be clearer as a result.

Now when I look at feedback sent, it doesn't really fit in with the pattern of existing messages and only works if a user adds a written message, so for consistency and simplicity ley's have the default success message as "Response moderated". This feels accurate whether a user has supplied a feedback message or not.

The "Response resubmitted" here I'm afraid to say is an error, it should say "Response submitted " .   "Response resubmitted" is only shown when a user edits a response which previously failed moderation, which I believe is beyond the scope of this work.

So let's summaries:

| Success message        | Occurs when...             |
| --------------------------------- |--------------|
| Response approved     | a Moderator or Super Moderator clicks the insta "Approve" button |
| Response moderated     | a response is moderated, regardless of whether it contains written feedback or not   |
| Response submitted | any user who submits a response to a Play Store review |
| Response resubmitted | a user edits a response which previously failed moderation (implemented when we add the notifications inbox)    |

I hope that's clearer 😅

**Comment by rleitan** [comment]
> Response moderated	a response is moderated, regardless of whether it contains written feedback or not
>
<"Feedback sent" message is displayed when a response it's moderated and a feedback message is added

@M-erb this one should be fixed

> Response submitted	any user who submits a response to a Play Store review
> Response resubmitted	a user edits a response which previously failed moderation (implemented when we add the notifications inbox)
