### ISSUE TITLE
A moderator/super moderator is not able to moderate when a feedback message is added

### ISSUE THREAD

**Issue by rleitan** [mozilla/m-response#392]
[Precondition]:
Log in with a moderator or super moderator account

[STR]:
1.Open https://mresponse-staging.herokuapp.com/dashboard/
2.Click Moderate
3.Select a response to moderate
4.Click the black "Moderate" button
5.Select the feedback emoticons and add a feedback message
6.Click the "Submit" button

[Expected result]:
The moderation should be done

[Actual result]:
"Unable to submit moderation"  red banner is displayed for a second

[Note]:
A moderator/super moderator is able to submit a moderation without a feedback message
A normal user is able to submit a moderation with a feedback message

**Comment by M-erb** [comment]
Did this requirement change? I ask as this functionality was already existed on the front end and the back end before I started on this project.

The way I understand how it should work( again this was already build not by me) is:

- A moderator/super moderator is able to but not required to submit a moderation with a feedback message
- A normal user is NOT able to submit a moderation with a feedback message and therefore cannot see the feedback field at all.

**Comment by M-erb** [comment]
So any user at all can submit a feedback message? A regular user, a moderator gourp1, and group2. Is that right?

**Comment by madasan** [comment]
Only mod1 and mod2 group users can add a feedback message.
