### ISSUE TITLE
User is able to moderate own response

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/m-response#394]
**Env:**
iOS 13.0, Firefox and Safari

**STR:**
1. Login to respond tool as a contributor
2. Navigate to Response page
3. Submit a response for an existing review
4. Navigate to the Moderate section
5. Navigate through the existing responses, including the last page

**Expected:**
The response added in step 3 is not in the list of responses to moderate

**Actual:**
The response added in step 3 is in the list of responses to moderate, on the last page
See [video](https://drive.google.com/file/d/1a4GhU-gfrTPms63fUaSCh4eKzIkD0jqe/view?usp=sharing)

**Comment by M-erb** [comment]
Tested on staging and locally on latest updates and do not see this happening currently. Will move this to test again once the latest is pushed into staging.

**Comment by viorelaioia** [comment]
@M-erb , this is still happening. Note that you have to be a contributor in order to reproduce the issue. Can you try again?

**Comment by M-erb** [comment]
I was able to confirm this happening. Two things that need to be corrected with this:

1. A review I responded to is showing up inside of the moderation queue.
2. As that same user that responded I can submit a moderation on it.

**Comment by viorelaioia** [comment]
User is still able to moderate his own response via the public API.

**Steps:**
1. Login as a contributor
2. Respond to a review 
3. In a new tab, try the API endpoint for retrieving info on the specific response: https://mresponse-staging.herokuapp.com/api/response/339/ => Returns "Not found"
4. In a new tab, try the API endpoint for moderating the response: https://mresponse-staging.herokuapp.com/api/moderation/create/339/

**Expected:**
User is not allowed to moderate the response via the api

**Actual:**
User can check the checkboxes for the 3 feedback values and submit the change. In the admin interface, the response is shown as moderated by contributor.
