### ISSUE TITLE
Progress percentages show unexpected results

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/m-response#400]
Progress shows the difference between current week and last week on positives vote for tone, issue and personal. I would expect the numbers would not go below 0%. Though I have a value of "-125%" displayed on my profile. 

![photo_2019-09-24_11-37-48](https://user-images.githubusercontent.com/5293100/65525490-3f7e2c80-def8-11e9-9607-ae2e3077cc16.jpg)

**Comment by vbabiy** [comment]
We have 2 time frames a current and a previous:
- Current is now to 7 days ago.
- Previous is 14 days ago to 7 days ago

The change is calculated with the following logic:

If the current is tone is 7 and previous was 10 we show -30%
If the current tone is 5 and previous was 5 we will show a 0%
If the current tone is 10 and previous was 7 we will show a 43%

Forumal:

`(current - previous) / prevous`
