### ISSUE TITLE
The uploaded photo is rotated

### ISSUE THREAD

**Issue by rleitan** [mozilla/m-response#402]
[Environment]:
Android ver.9 

[STR]:
1.Go to https://mresponse-staging.herokuapp.com/profile/
2.Tap the upload picture
3.Upload a picture ( take a picture or select a picture from photo gallery)

[Expected result]:
The picture should be uploaded and correctly positioned

[Actual result]:
The picture is uploaded but is rotated 90 degrees to the left

[Note]:
The issue is not reproducible on iOS

**Comment by M-erb** [comment]
I tested this in both firefox and chrome on the staging site and could not reproduce the issue.

Device (moto g6 play) Android version 9
Firefox(68.1.1)
chrome(77.0.3865.92)

**Comment by rleitan** [comment]
I just reproduced it on Firefox Nightly for Android.

**Comment by ipmb** [comment]
@rleitan Are you seeing this only with a specific image or any image you upload? If it is a specific image, could you share it here?

I'm wondering if there is EXIF data in the image the specifies it should be rotated. https://www.daveperrett.com/articles/2012/07/28/exif-orientation-handling-is-a-ghetto/
