### ISSUE TITLE
The grayed out response is never displayed as available to respond

### ISSUE THREAD

**Issue by rleitan** [mozilla/m-response#403]
[STR]:
1.Go to https://mresponse-staging.herokuapp.com/respond/
2.Click the Skip button several times

[Expected result]:
The greyed out response (e.g. - "Madalina") should be displayed 

[Actual result]:
The grayed out response is never displayed as ready to respond
The response order when clicking "Skip" button is random

https://drive.google.com/file/d/1-SPj6cAQVjOAffpTBQ8d2DiqWp2-Av7e/view?usp=sharing

**Comment by M-erb** [comment]
This is related to issue #389

**Comment by rleitan** [comment]
I reproduced this issue: https://drive.google.com/file/d/1R_SbJX04cLAGTFDU9VuquVEn2qAS-CP1/view
