### ISSUE TITLE
A response moderated by 3 contributors is not approved

### ISSUE THREAD

**Issue by rleitan** [mozilla/m-response#407]
[Precondition]:
Add a response from a contributor account

[STR]:
1.Moderate the response from precondition with 3 yes from a contributor account
2.Moderate the response from precondition with 3 yes from a contributor account
3.Moderate the response from precondition with 3 yes from a contributor account

[Expected result]:
The response should have "Approved" checkbox checked in the admin interface

[Actual result]:
The response has 3 moderations but is not "Approved"

**Comment by madasan** [comment]
This is the logic that should be used for moderation by regular users:

![image](https://user-images.githubusercontent.com/10244340/65765762-cec25480-e131-11e9-955a-6cb2e6ca9938.png)
