### ISSUE TITLE
The response moderated by 3 super moderators is not approved 

### ISSUE THREAD

**Issue by rleitan** [mozilla/m-response#423]
[Precondition]:
Add a response from moderator 1 account

[STR]:
1.Moderate the response from 3 super moderator 2 accounts as displayed in the [table](https://github.com/mozilla/m-response/issues/407)

[Expected result]:
The response should be automatically approved ( because is added from moderator 1 account)
The response should have Staff approved checkbox checked after 3 moderations

[Actual result]:
The response is approved but the Staff approved checkbox is not checked

**Comment by vbabiy** [comment]
@madasan I don't think this was a requirement, am I wrong?

**Comment by rleitan** [comment]
Verified as fixed!
