### ISSUE TITLE
Rejected response is still displayed in Super Moderator "Moderate" queue

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/m-response#424]
**STR:**
1. Add a response to a review while logged in as a contributor
2. Login with 3 contributor accounts and moderate the response added in step 1 with NO feedback value for Friendly, Technical, Reusable
3. Login in as a Super Moderator and search for the response added in step 1 in the Moderation queue

**Expected:**
As per Moderation [schema](https://miro.com/app/board/o9J_kw6tbs8=/), the response should be rejected and the review should be empty and displayed again in the Respond section

**Actual:**
Response is displayed in the Moderation queue of the Super Moderator

CC @madasan

**Comment by viorelaioia** [comment]
The review is still not displayed in the Respond section, even though the review has no response associated (the existing one is rejected)

**Comment by johngian** [comment]
Hi the problem here is that the response might be filtered as rejected, but the review still has an assigned response to it. Should we delete responses that are actually rejected? Or do we need them for historical reasons

@madasan thoughts?

**Comment by madasan** [comment]
Let's keep them for historical reasons.

**Comment by rleitan** [comment]
Verified as fixed!
