### ISSUE TITLE
Sometimes the review is still displayed in Response section after adding a response

### ISSUE THREAD

**Issue by rleitan** [mozilla/m-response#429]
[STR]:
1.Go to Respond section
2.Add a response and click "Submit for moderation" button

[Expected result]:
The response should be submitted and should not be displayed anymore in Respond section

[Actual result]:
The review is still displayed in the Response section after adding a response
The added response is not displayed in the admin interface

https://drive.google.com/file/d/1bK9sf5FJRNhN1zhtGsv4gLOAcfiQaGhU/view

**Comment by johngian** [comment]
I think i fixed the issue where you needed to submit 2 times the last response. Can you take a look again? I am not sure if its fixed for your case.

**Comment by rleitan** [comment]
I cannot reproduce it anymore! seems like it's fixed
