### ISSUE TITLE
User receives +1 karma point when adding a response

### ISSUE THREAD

**Issue by rleitan** [mozilla/m-response#430]
[STR]:
1.Go to Respond
2.Add a response

[Expected result]:
Karma point should be received only when the response it's approved

[Actual result]:
User  receives +1 karma point when adding a response

**Comment by vbabiy** [comment]
@rleitan Did you see this on the backend, frontend, or both?

**Comment by rleitan** [comment]
both
@vbabiy

**Comment by johngian** [comment]
@rleitan can you check again? I tried to reproduce this but on stage but:

* Karma is 16
* Respond to a review
* Go back to profile
* Karma is still 16

**Comment by rleitan** [comment]
I tested this again with all account types and couldn't reproduce it. Closing the issue
