### ISSUE TITLE
Approved response is still displayed in Moderator 2 "Moderate" section 

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/m-response#434]
**Preconditions:**
Have a response approved

**STR:**
Login to respond tool with a Moderator 2 account that is not Staff
Navigate to Moderate section
Search after approved responses from precondition

**Expected:**
The approved response is not displayed in the Moderate list, it is displayed only for admins in the admin interface

**Actual:**
The approved response is displayed in the Moderate list

**Comment by viorelaioia** [comment]
@johngian , that is the problem. The response approved should not be available in the Moderator 2 "Moderate" list, but only in the admin interface for people with staff status to approve it. 
@madasan , can you also confirm this?
Thanks!

**Comment by johngian** [comment]
Yeah, sorry I misread the bug. @madasan what do you think ?

**Comment by madasan** [comment]
If a response has been approved by the community it should not show up in the queue. It should only show up in the admin for staff approval.
Mod 2 cannot upload per se, responses are uploaded automatically when clicking "Submit".
