### ISSUE TITLE
Remove [bracketed text] from the start of some common responses

### ISSUE THREAD

**Issue by SeburoSUMO** [mozilla/m-response#476]
Please can some of the common responses be edited to remove the [TEXT].  This would save a contributor having to edit this out manually when used one of those responses in a reply to a Google Play store review.

Examples (not the full list):

![image](https://user-images.githubusercontent.com/31939113/77956147-4d5aa300-72c9-11ea-9895-186a78e3a279.png)

**Comment by rugk** [comment]
Did not saw this again, seems to be fixed.

**Comment by plwt** [comment]
I agree, this appears to be fixed.
