### ISSUE TITLE
Contributor stats look a bit odd

### ISSUE THREAD

**Issue by SeburoSUMO** [mozilla/m-response#516]
Hi

Last week I did about 100 - 120 responses, but the Respond tool has me down as doing 496:

![image](https://user-images.githubusercontent.com/31939113/89216327-18859200-d5c2-11ea-8c11-208c57154564.png)

I am not sure what it is counting but this does not look right.

**Comment by kelimuttu** [comment]
Hey Paul, 

Thanks for your report. We noticed that as well and we think it's the monthly/overall stats instead of weekly. 

@madasan FYI

**Comment by SeburoSUMO** [comment]
Every time I answer 1, each of the feedback stats in my profile show an increase of 3.

I think that this is then added to the previous week's total so that the "weekly total" is not even close to overall stats.

**Comment by kelimuttu** [comment]
In that case, I suppose it came from the karma calculation instead of pure "contribution number".

**Comment by LeoMcA** [comment]
The issue was that we counted automatically generated self-moderations created when users are a moderator 1 or 2 and reply.

Fix is deployed, you should see an accurate leaderboard once the cache has expired (which should be within the hour).
