### ISSUE TITLE
Google Play reviews are partially covered by "Mozillian Response" div causing some review text to be hidden

### ISSUE THREAD

**Issue by NoahSUMO** [mozilla/m-response#525]
Hi. It appears one innocent bug slipped thru our [June Respond Bug Hunt campaign](https://community.mozilla.org/en/events/respond-tool-campaign-help-us-file-bugs/). I'm pretty sure I would've spotted this one in time if I had known about that event. Since I noticed this bug on Day 1 of our Play Store Support Campaign 😛 D'oh!

Bug:
The 2nd half of a Google Play review gets hidden by the Mozillian Response section. But only if the reviews go over a certain length. Short reviews will always be shown in full. Seems to be a problem only for the Moderators. It looks like a simple CSS fix I believe. By making the review div auto-flex/expand to the entire height of that text area or maybe the div below has a fixed position. Sorry if I'm getting any terms wrong here, I should learn more webdev to get this stuff right. :)

Screenshot of the bug:
![Screen Shot 2020-08-10 at 1 54 27 PM](https://user-images.githubusercontent.com/5785249/89885066-16a66a80-db90-11ea-955f-0b9e7cf7393f.png)

**Comment by LeoMcA** [comment]
Thanks for reporting this @NoahSUMO, actually this slipped through the cracks on our side, we already [had a report of this](https://github.com/mozilla/sumo-project/issues/522), so apologies for that!

> It looks like a simple CSS fix I believe.

Indeed, a very simple CSS fix thankfully. Waiting on the deployment to stage, and will then push it to prod if all goes well there.

**Comment by NoahSUMO** [comment]
Awesome! Thanks so much for quick turnaround on this. I understand, so many bugs, so little time to fix them all!

**Comment by kelimuttu** [comment]
yay! Thank you for a quick fix on this @LeoMcA

**Comment by Timmaks** [comment]
Thanks for the quick fix!

**Comment by LeoMcA** [comment]
Should now be live in prod, you might need to do a hard refresh to pull the new CSS in.

**Comment by Timmaks** [comment]
Thanks. Everything looks ok now.
