### ISSUE TITLE
Submit response to playstore BE

### ISSUE THREAD

**Issue by abigail-hampson** [mozilla/m-response#54]
- [ ] criteria when response can be submitted to playstore - confirm with Mozilla
- [ ] Probably add an env variable to quickly switch off feature if needed - we need to be careful with the keys since they can do a lot of damage.

**Comment by geroter** [comment]
3 Passes = Pass | Positive tone (requires 3/3) | Does it address the issue set out in the review (⅔) | Personalized (⅓)
-- | -- | -- | --
Reviewer 1 | ✓ | X | X
Reviewer 2 | ✓ | ✓ | X
Reviewer 3 | ✓ | ✓ | ✓
  | Pass | Pass | Pass

**Comment by tm-kn** [comment]
@geroter we have not discussed rejecting the responses properly. Is there a flow for that at all? Or is that a separate concern?

**Comment by tm-kn** [comment]
@johngian suggested to add an environment variable to turn replying off and on. Just added it on the checklist.

**Comment by geroter** [comment]
Can you clarify so that I can be sure I understand?

**Comment by tm-kn** [comment]
@geroter Sorry. As in, what happens if the response is genuinely bad and it only gets negative response. Do we delete all together? Do we have to do anything about it at all?

**Comment by geroter** [comment]
By response you mean the Google Review? Or the response that someone has written in the app?

For the response that someone has written in the app --> I think that if it's bad/rejected, we should retain, but say that it's rejected, and then put the Google Review back in the queue for answering.

**Comment by kaedroho** [comment]
Hi @geroter 

When there are > 3 moderations, how do the above rules apply?

For example, should we be looking for any three moderations that have"positive in tone" checked, or are we checking that 100% of moderations have "positive in tone" checked?
