### ISSUE TITLE
Mixed locales on the old backlog

### ISSUE THREAD

**Issue by kelimuttu** [mozilla/m-response#550]
When the within-3-days queue is done and we're back on the backlog, I find that I'm being presented with lots of non-English reviews although I choose only English.

**Comment by LeoMcA** [comment]
Can you check what the locale is listed as in the admin panel for these reviews? We filter on the locale Google sends us, and occasionally that's wrongly listed as English when the review isn't in English. There's not much we can do about this.

**Comment by kelimuttu** [comment]
You're right. They're using English in their device. Let me close this in the meantime.
