### ISSUE TITLE
More canned responses

### ISSUE THREAD

**Issue by rugk** [mozilla/m-response#556]
Some common ones I saw:

#### a combined complain and forum version

> Hi, we’re sorry that you’re unhappy with the new Firefox. We are continually making improvements to the new version. Thank you for providing feedback that will help us make Firefox better.
If you do have a problem, feel free to ask ask in our Support Forum https://mzl.la/3ilTiS4.

#### about:config

> Thank you for your feedback. about:config is supported in Nightly versions of Firefox for Android. See https://mzl.la/31TG1Kf for more information.

#### PDF download 

> Thank you for your feature request. A PDF download is currently in development. See https://mzl.la/31WnAV8 for more information.
> If you have further questions, feel free to ask ask in our Support Forum https://mzl.la/3ilTiS4.

#### View source

> Thank your for your feature request. The ability to view a source code may be added in the future. For now you can use an add-on in Nightly, see https://mzl.la/2Gdkwwc for more information.

**Comment by kelimuttu** [comment]
Hi @rugk, 

Thank you for suggesting these. I'll take the action item to propose these to the product team. Will update here once I get the approval. 

Once again, thank you!

**Comment by kelimuttu** [comment]
@LeoMcA can you assign this to me?

**Comment by kelimuttu** [comment]
@rugk After some minor edits, these have been added under the Negative and Missing Features category. 

@LeoMcA I think we're good to close this issue.
