### ISSUE TITLE
Update password validation

### ISSUE THREAD

**Issue by abigail-hampson** [mozilla/m-response#66]

**Comment by geroter** [comment]
Password should be at least 8 characters long and contain at least 1 number.

**Comment by madasan** [comment]
Current password validation rules on support.mozilla.org: Password must be at least 8 characters and contain at least one letter and one number

**Comment by kaedroho** [comment]
There's some tighter password validation rules being enforced somewhere (I'm guessing in Auth0 itself):

> Error: * At least 8 characters in length * Contain at least 3 of the following 4 types of characters: * lower case letters (a-z) * upper case letters (A-Z) * numbers (i.e. 0-9) * special characters (e.g. !@#$%^&*)

This would need to be changed to match the same rules that we're implementing in the app.
